# https://taskfile.dev

version: '3'

tasks:
  backend-build:
    desc: Build backend
    dir: backend
    cmds: [go build -o build/pokcli-backend]

  backend-run:
    desc: Run backend
    dir: backend
    deps: [backend-build]
    cmds: [./build/pokcli-backend]

  cli-build:
    desc: Build frontend
    dir: frontend
    cmds: [go build -o build/pokcli]

  cli-run:
    desc: Run backend
    dir: frontend
    deps: [cli-build]
    cmds: [./build/pokcli]
