name: Build

on: [push]

jobs:

  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Generate proto code
        run: |
          export PATH="$PATH:/opt/hostedtoolcache/protoc/v23.4/x64"
          task proto-gen

      - name: Build backend
        run: task backend-build

      - name: Build frontend
        run: task frontend-build
